# build_shaders.ps1 — 使用 fxc 编译 HLSL 着色器并生成内嵌头文件
param(
    [string]$ShaderDir,
    [string]$OutputHeader
)

$ErrorActionPreference = "Stop"

if (-not (Test-Path $ShaderDir)) {
    Write-Error "Shader directory not found: $ShaderDir"
    exit 1
}

# 查找 fxc.exe
$fxc = $null
$fxcPaths = @(
    "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.22621.0\x64\fxc.exe",
    "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.22000.0\x64\fxc.exe",
    "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.19041.0\x64\fxc.exe",
    "${env:ProgramFiles(x86)}\Windows Kits\10\bin\10.0.18362.0\x64\fxc.exe"
)
# 也尝试从环境变量路径自动发现
$kitBin = "${env:WindowsSdkDir}bin" + "${env:WindowsSDKVersion}\x64\fxc.exe"
if ($kitBin) { $fxcPaths = @($kitBin) + $fxcPaths }

foreach ($p in $fxcPaths) {
    if (Test-Path $p) { $fxc = $p; break }
}

if (-not $fxc) {
    # 最后尝试从 PATH 查找
    $which = Get-Command fxc.exe -ErrorAction SilentlyContinue
    if ($which) { $fxc = $which.Source }
}

if (-not $fxc) {
    Write-Error "fxc.exe not found. Please install Windows SDK"
    exit 1
}

Write-Host "fxc.exe: $fxc"

# 着色器文件名 → 编译 profile 映射
$profiles = @{
    "vs_basic"      = "vs_5_0"
    "ps_basic"      = "ps_5_0"
    "vs_sdf"        = "vs_5_0"
    "ps_sdf"        = "ps_5_0"
    "vs_text"       = "vs_5_0"
    "ps_text"       = "ps_5_0"
    "vs_blur"       = "vs_5_0"
    "ps_blur"       = "ps_5_0"
    "ps_sdf_clip"   = "ps_5_0"
}

$hlslFiles = Get-ChildItem -Path $ShaderDir -Filter "*.hlsl"
if ($hlslFiles.Count -eq 0) {
    Write-Error "No .hlsl files found in $ShaderDir"
    exit 1
}

# 存放编译产物的临时目录
$csoDir = Join-Path (Split-Path $OutputHeader -Parent) "shader_cso"
New-Item -ItemType Directory -Force -Path $csoDir | Out-Null

$entries = @()

foreach ($file in $hlslFiles) {
    $baseName = [System.IO.Path]::GetFileNameWithoutExtension($file.Name)
    if (-not $profiles.ContainsKey($baseName)) {
        Write-Warning "Skipping unknown shader: $($file.Name)"
        continue
    }
    $profile = $profiles[$baseName]
    $csoFile = Join-Path $csoDir "$baseName.cso"

    Write-Host "Compiling $($file.Name) -> $baseName.cso  (/$T $profile)"
    # Use cmd /c to avoid PowerShell treating fxc stderr as errors
    $fxcArgs = "/T $profile /O3 /nologo /Fo `"$csoFile`" `"$($file.FullName)`""
    $proc = Start-Process -FilePath $fxc -ArgumentList $fxcArgs -NoNewWindow -Wait -PassThru -RedirectStandardOutput "$env:TEMP\fxc_out.txt" -RedirectStandardError "$env:TEMP\fxc_err.txt"
    $stdout = Get-Content "$env:TEMP\fxc_out.txt" -ErrorAction SilentlyContinue
    $stderr = Get-Content "$env:TEMP\fxc_err.txt" -ErrorAction SilentlyContinue

    if ($proc.ExitCode -ne 0) {
        Write-Error "fxc failed with exit code $($proc.ExitCode): $($file.Name)"
        if ($stdout) { Write-Host $stdout }
        if ($stderr) { Write-Host $stderr }
        exit 1
    }
    # Print warnings if any
    if ($stdout -and $stdout -match '\S') { Write-Host $stdout }
    if ($stderr -and $stderr -match '\S') { Write-Host "WARNING: $stderr" }

    if (-not (Test-Path $csoFile)) {
        Write-Error "fxc did not produce output: $csoFile"
        exit 1
    }

    # 读取编译后的字节码
    $bytes = [System.IO.File]::ReadAllBytes($csoFile)
    $varName = "g_" + $baseName + "_bytecode"
    $size = $bytes.Length

    $entries += @{
        VarName = $varName
        Size    = $size
        Bytes   = $bytes
    }
}

# 生成 C++ 头文件
$headerDir = Split-Path $OutputHeader -Parent
New-Item -ItemType Directory -Force -Path $headerDir | Out-Null

$sb = [System.Text.StringBuilder]::new()
$timestamp = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
[void]$sb.AppendLine("// ShaderBytecode.h - auto-generated by build_shaders.ps1 at $timestamp")
[void]$sb.AppendLine("// Pre-compiled D3D11 shader bytecode arrays")
[void]$sb.AppendLine("#pragma once")
[void]$sb.AppendLine("#include <cstdint>")
[void]$sb.AppendLine("#include <cstddef>")
[void]$sb.AppendLine("")
[void]$sb.AppendLine("namespace mine::gfx::d3d11::shaders {")
[void]$sb.AppendLine("")

foreach ($entry in $entries) {
    [void]$sb.AppendLine("// $($entry.VarName) - $($entry.Size) bytes")
    [void]$sb.AppendLine("inline constexpr uint8_t $($entry.VarName)[] = {")
    $hexLines = ""
    for ($i = 0; $i -lt $entry.Bytes.Length; $i++) {
        $hexLines += "0x{0:X2}," -f $entry.Bytes[$i]
        if (($i + 1) % 16 -eq 0 -and $i -lt $entry.Bytes.Length - 1) {
            $hexLines += "`n    "
        }
    }
    $hexLines = $hexLines.TrimEnd(',')
    [void]$sb.AppendLine("    $hexLines")
    [void]$sb.AppendLine("};")
    [void]$sb.AppendLine("")
}

[void]$sb.AppendLine("} // namespace mine::gfx::d3d11::shaders")

[System.IO.File]::WriteAllText($OutputHeader, $sb.ToString(), [System.Text.UTF8Encoding]::new($true))
Write-Host "`nOK: $OutputHeader ($($entries.Count) shaders)"
